### ISSUE TITLE
Maintaining version wise documentation

### ISSUE THREAD

**Issue by kidrahahjo** [glotzerlab/signac-docs#118]
### Issue Description
When we remove any class/function from **signac** or **signac-flow**, the API documentation for those function also gets removed. (This is because we have an API reference for the docs)
In `flow` version 0.13, we will remove classes and methods like `JobOperation`, `next_operations`, `run_operations`, etc. Some of our users may choose to not install the latest version and this would mean that they won't be able to find documentation of the removed methods/classes. 

### Proposed change (optional)
I propose to maintain a version wise documentation. If we choose not to have a separate documentation page for every version, we can provide documentation pdfs for all the major releases as well.

**Comment by mikemhenry** [comment]
This is a great idea and we do maintain version documentation! You have to select the API documentation for a package, but in the bottom left you can choose the version of docs you want.
![Screenshot from 2021-02-12 05-39-01](https://user-images.githubusercontent.com/11765982/107769087-a5897080-6cf4-11eb-91b3-219a92c27b05.png)

**Comment by kidrahahjo** [comment]
This is great, I might have missed this. Thanks @mikemhenry for letting me know. I am going to close this now!

**Comment by mikemhenry** [comment]
No worries! It doesn't show up when on the "main" docs page so it is easy to miss.
