### ISSUE TITLE
Query docs should not show `doc_filter`

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-docs#153]
### Issue Description
This page describes `doc_filter`arguments, which should be removed.
https://docs.signac.io/en/latest/query.html#query-namespaces

This PR removes the `doc_filter` argument from the docs: https://github.com/glotzerlab/signac/pull/586

**Comment by cbkerr** [comment]
Searching the docs for `doc_filter` doesn't turn up anything, so closting this
