### ISSUE TITLE
Add link to code of conduct on community page 

### ISSUE THREAD

**Issue by mikemhenry** [glotzerlab/signac-docs#25]
We should probably add a link to https://signac.io/conduct/ on this page http://docs.signac.io/en/latest/community.html 

I expected to find it there, if others agree, I'll make the PR

**Comment by vyasr** [comment]
I agree, I also went looking for it and couldn't find it anywhere on our documentation. That seems to be the right place.

**Comment by mikemhenry** [comment]
Fixed with PR #28
