### ISSUE TITLE
Clarify role of directives in execution/submission

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-docs#38]
While discussing how to clarify directives, we decided to do the following:

1. Move the directives to a higher-level (and earlier) in the docs.
2. Rename "Execution Directives" to "Submission Directives."
3. Change the proposed `fork` behavior from https://github.com/glotzerlab/signac-flow/pull/132 to a decorator like `with_job` or `cmd` since it affects execution when running locally, unlike the other directives.
4. Reword the portion about parallelism so it's clear that we don't magically parallelize operations by adding `np=4`.

**Comment by csadorf** [comment]
Resolved with merge of #40 .
