### ISSUE TITLE
More examples and descriptive documentation for signac's H5store interface

### ISSUE THREAD

**Issue by klywang** [glotzerlab/signac-docs#50]
Currently, the documentation for `project.data` and `job.data` references the `H5Store` class rather than provide examples with the interface. The relationship between `H5Store`'s documentation and `job.data` and `project.data` may be unclear for new users. Examples for usage and information about the interface should appear under the documentation for `job.data` and `project.data` for clarity and ease of use.

It may help to warn users what data cannot be accessed without the context manager or more descriptive language to explain when a context manager is needed. Specifically, the line: "The H5Store **can** be used as a context manager to ensure that the underlying file is opened, **however most built-in types can be read and stored without the need to _explicitly_ open the file**" is ambiguous on the topic of how we need to access data.

**Comment by kidrahahjo** [comment]
@bdice @klywang 
I see two of the pull requests got merged which mentioned this issue.
Should we close this?

**Comment by bdice** [comment]
Yes, I think this is resolved.
