### ISSUE TITLE
HOOMD example should be an ideal gas

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-docs#51]
The HOOMD example claims to simulate an ideal gas, but it actually uses a Lennard-Jones fluid. The simplest solution to this problem would be to just remove the lj pair potential entirely from that bit of code.

**Comment by mikemhenry** [comment]
The example is actually supposed to be an LJ fluid and there is only one mention of an ideal gas, so instead I'm going to keep it LJ fluid and fix the mentions of ideal gas

**Comment by vyasr** [comment]
Resolved by #55
