### ISSUE TITLE
add a glossary for uncommon naming

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/signac-docs#59]
add a glossary for terms like: bundle, group, statepoint, workspace(?), aggregate.

**Comment by cbkerr** [comment]
Closing as we are refining definitions in the google doc and the [docs project](https://github.com/orgs/glotzerlab/projects/5/).

(For future reference, I don't think this is a good first issue because it requires a deep working knowledge of how the pieces of signac fit together.)

**Comment by csadorf** [comment]
@cbkerr Why would you close the issue if the work is still ongoing?

**Comment by cbkerr** [comment]
This is the link to the google docs glossary development: https://docs.google.com/document/d/1_merhcK3ohas4IloE616yL7gypMRFcaQLh2oChExC7o/edit?pli=1
