### ISSUE TITLE
Update logo badge on acknowledgement page.

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-docs#66]
The badge on https://docs.signac.io/en/latest/acknowledge.html still shows our old logo. This should be updated.

**Comment by mikemhenry** [comment]
Good catch! The sentence on the bottom of the page reads: 

>This means you can use logos as long as you attribute the logos to the relevant signac project.

But since we are only using one logo for the whole framework, we might want it to say something like:

>This means you can use logos as long as you attribute the logos to the  signac project.
