### ISSUE TITLE
Improve our signac-flow API visibility 

### ISSUE THREAD

**Issue by mikemhenry** [glotzerlab/signac-docs#75]
We have lots of things documented in flow but we don't render/show the documentation on our RTD page.

**Comment by mikemhenry** [comment]
We have this: https://docs.signac.io/en/latest/reference.html

But maybe need a way to organize the order/what topics people should check out.

**Comment by cbkerr** [comment]
@mikemhenry I'm not sure what level of detail in "things" you are referring to, but is this issue repeated in #95 and solved with #97? Do you want to include a list of functions from the API for flow?

**Comment by mikemhenry** [comment]
That is very unclear, sorry about that.I believe that much more of the API is now exposed on read the docs.
