### ISSUE TITLE
Update documentation for printing status

### ISSUE THREAD

**Issue by kidrahahjo** [glotzerlab/signac-docs#86]
### Issue Description
A recently merged PR [#271](https://github.com/glotzerlab/signac-flow/pull/271) introduces a new feature which enables parallelized determination of the project status with processes.
Here a configuration variable (`status_parallelization`) was introduced.
We would now want to update the official documentation accordingly for the new users to learn about the feature.

### Additional context
This was originally suggested by @csadorf, I'll take this forward from here.

**Comment by csadorf** [comment]
Thank you @kidrahahjo !
