### ISSUE TITLE
Add details about why users want each package to framework installation instructions

### ISSUE THREAD

**Issue by cbkerr** [glotzerlab/signac-docs#96]
### Issue Description
We have redundant instructions on [this site](https://docs.signac.io/en/latest/installation.html) but also [signac-core](https://docs.signac.io/projects/core/en/latest/installation.html) and [signac-flow](https://docs.signac.io/projects/flow/en/latest/installation.html) and [signac-dashboard](https://docs.signac.io/projects/dashboard/en/latest/installation.html) (all links are to "installation".)

The installation tab in signac-docs clutters our sidebar and detracts from the purpose of the integrated documentation, which is to show how the pieces fit together. 

### Proposed change

We had discussed removing the installation instructions in this week's signac dev meeting. Keep installation instructions only within each package. Link to each installation page directly from the getting started page and the package list page.

**Comment by cbkerr** [comment]
Perhaps we can include the simplest installation command on the new "Packages" page but redirect to the separate pages for more advanced ways.

**Comment by csadorf** [comment]
I may be missing some context, because I was not part of the discussion at the meeting, however I would like to point out that having a super clear and easy path to installation is essential in on-boarding new users. A new user will likely spend only about a minute max to find instructions on how to install signac and "hiding" the installation instructions on various sub packages may therefore be detrimental. I believe that some duplication is fine if that makes it easier to on-board new users, especially because it is so easy to install signac.

**Comment by cbkerr** [comment]
Looking back at this, I agree that we need a clear "Installation" keyword for new users who are skimming for how to get started. Coupled with the fact that the "installation" link on signac.io points to the installation page on the framework documentation, I think at best it's too early to remove the installation page from the side bar.

There is some additional context in the discussion at #85.

**Comment by klywang** [comment]
@csadorf I agree that we need a to keep "Installation" on the side bar and that information provided there should be concise. If I remember correctly from my offline discussion with @cbkerr, the main concern was new users who skipped straight to "Installation". The presence of multiple packages and there functions seems to be a consistent entry barrier (at least from my anecdotal experience).

Currently, this is what you see first on the "Installation" page:
![image](https://user-images.githubusercontent.com/47036428/89819184-fe473900-db18-11ea-8972-3e2501986fbe.png)

We may want to reiterate the contents of the "Packages" section, but focus on why you want to download them/what they can be used for. Something along the lines of:

**Installation**
The **signac framework** consists of three package. Users may install packages based on needed functionality (see Packages for more information): 

- the core **signac** package: 
    - implement your own, file based database
    - search and manipulate data in existing **signac** databases
    - provides the data management functionality for **signac-flow** and **signac-flow** 
- **signac-flow**: 
    - implement workflows on databases managed with **signac**
    - run complex workflows from the command line
    - submit jobs to high-performance clusters (HPC)
    - requires **signac** core package
- **signac-dashboard**:  
    - share workspaces through a browser-based GUI
    - requires **signac** core package

Most users should install the **signac** and the **signac-flow packages**, which are tested for Python 3.5+ and are built for all major platforms. Please see the individual package documentation for instructions on how to install additional packages.

**Comment by kidrahahjo** [comment]
@klywang @cbkerr I believe the changes are pending with respect to this issue.
Since it's a small change, should I go ahead and work on this if you're busy with your schedule?

**Comment by klywang** [comment]
@kidrahahjo sorry about the late reply. Go ahead!

**Comment by cbkerr** [comment]
That would be great @kidrahahjo, thank you!

For visual appeal, it might be nice to add to [Kelly's outline](https://github.com/glotzerlab/signac-docs/issues/96#issuecomment-671549486)  the badges of the packages ([as currently displayed on the Packages page](https://docs.signac.io/en/latest/packages.html)). It would be duplicate info, but I think relevant in both cases.
